// web/src/routes/account/login/index.tsx
import { login } from "@api/account";
import { getAuthConfig } from "@api/platform";
import LogoAnimate from "@assets/animates/logo-animate";
import xdu from "@assets/brands/xdu.svg";
import xmu from "@assets/brands/xmu.svg";
import xdsecMascotCrying from "@assets/imgs/xdsec-mascot-crying.webp";
import xdsecMascotHappy from "@assets/imgs/xdsec-mascot-happy.webp";
import xdsecMascotNormal from "@assets/imgs/xdsec-mascot-normal.webp";
import xdsecMascotUnsee from "@assets/imgs/xdsec-mascot-unsee.webp";
import Captcha from "@blocks/captcha";
import type { AuthConfig } from "@models/config";
import { createForm, minLength, pattern, required, setValue } from "@modular-forms/solid";
import { A, useLocation, useNavigate } from "@solidjs/router";
import { accountStore } from "@storage/account";
import { Title } from "@storage/header";
import { platformStore } from "@storage/platform";
import { t } from "@storage/theme";
import { addToast } from "@storage/toast";
import Button from "@widgets/button";
import Card from "@widgets/card";
import Divider from "@widgets/divider";
import Input from "@widgets/input";
import Link from "@widgets/link";
import type { HTTPError } from "ky";
import { DateTime } from "luxon";
import { Match, Show, Switch, createMemo, createSignal } from "solid-js";

type LoginForm = {
  account: string;
  password: string;
  captcha_id: string;
  captcha_answer: string;
};

export default function () {
  const navigate = useNavigate();
  const location = useLocation();
  if (accountStore.token) {
    navigate("/", { replace: true });
    return null;
  }
  const [form, { Form, Field }] = createForm<LoginForm>();
  const [authConfig, setAuthConfig] = createSignal({
    signing_key: "",
    buffer_time: 0,
    expires_time: 0,
    oauth_keys: {},
  } as AuthConfig);
  getAuthConfig()
    .then((config) => setAuthConfig(config))
    .catch(() => {});
  const oauthServices = createMemo(() => Object.keys(authConfig().oauth_keys || {}));
  const [mascot, setMascot] = createSignal(null as string | null);
  const [loading, setLoading] = createSignal(false);
  const [timestamp, setTimestamp] = createSignal(DateTime.now().toMillis());
  function handleLogin(result: LoginForm) {
    setLoading(true);
    setTimeout(() => {
      login(result)
        .then(() => {
          addToast({
            level: "success",
            description: t("account.login.success")!,
            duration: 5000,
            img: xdsecMascotHappy,
          });
          const redirectUrl = location.query.redirect;
          if (redirectUrl) {
            navigate(redirectUrl, { replace: true });
          } else {
            navigate("/", { replace: true });
          }
        })
        .catch((err: HTTPError) => {
          void err.response.text().then((text) => {
            addToast({ level: "error", description: text, duration: 5000 });
          });
          setTimestamp(DateTime.now().toMillis());
          setValue(form, "password", "");
          setTimeout(() => {
            setMascot(xdsecMascotCrying);
          }, 500);
        })
        .finally(() => {
          setLoading(false);
        });
    }, 500);
  }
  return (
    <>
      <Title title={`${t("account.login.title")} - ${platformStore.config.name || t("platform.name")}`} />
      <div class="flex-1 flex flex-col items-center md:justify-center p-3 md:p-6">
        <Card
          class="w-full max-w-3xl"
          contentClass="p-6 flex flex-col md:flex-row space-y-2 space-x-0 md:space-x-6 md:space-y-0"
        >
          <Form onSubmit={handleLogin} class="md:w-0 flex-1 flex-shrink-0 flex flex-col space-y-2">
            <h2 class="font-bold text-center">{t("account.login.title")}</h2>
            <Field
              name="account"
              validate={[
                required(t("account.login.accountRequired")!),
                minLength(4, t("account.login.accountMinLength")!),
              ]}
            >
              {(field, props) => (
                <Input
                  icon={<span class="icon-[fluent--person-20-regular] w-5 h-5" />}
                  placeholder={t("account.login.accountPlaceholder")}
                  title={t("account.login.accountPlaceholder")}
                  autocomplete="username"
                  {...props}
                  value={field.value}
                  error={field.error}
                  required
                  onFocusIn={() => {
                    setMascot(xdsecMascotNormal);
                  }}
                  onFocusOut={() => {
                    setMascot(null);
                  }}
                />
              )}
            </Field>
            <Field
              name="password"
              validate={[
                required(t("account.login.passwordRequired")!),
                minLength(8, t("account.login.passwordMinLength")!),
                pattern(
                  // biome-ignore lint/correctness/noEmptyCharacterClassInRegex: password allows any characters
                  /^(?=.*[a-z])(?=.*[A-Z])(?=.*\d)[^]{8,40}$/,
                  t("account.login.passwordTooWeak")!
                ),
              ]}
            >
              {(field, props) => (
                <Input
                  icon={<span class="icon-[fluent--lock-20-regular] w-5 h-5" />}
                  type="password"
                  placeholder={t("account.login.passwordPlaceholder")}
                  title={t("account.login.passwordPlaceholder")}
                  extraLabel={
                    <A href="/account/forgot" class="hover:underline flex items-center space-x-1">
                      <span class="icon-[fluent--question-circle-16-regular] w-4 h-4 text-primary" />
                      <span>{t("account.forgot.title")}</span>
                    </A>
                  }
                  autocomplete="current-password"
                  {...props}
                  value={field.value}
                  error={field.error}
                  onFocusIn={() => {
                    setMascot(xdsecMascotUnsee);
                  }}
                  onFocusOut={() => {
                    setMascot(null);
                  }}
                />
              )}
            </Field>
            <Field name="captcha_id">
              {(idField) => (
                <Field
                  name="captcha_answer"
                  validate={[required(t("captcha.required")!), minLength(4, t("captcha.minLength")!)]}
                >
                  {(answerField, props) => (
                    <Captcha
                      {...props}
                      captchaForm={form}
                      idFieldValue={idField.value}
                      idFieldError={idField.error}
                      answerFieldValue={answerField.value}
                      answerFieldError={answerField.error}
                      timestamp={timestamp()}
                    />
                  )}
                </Field>
              )}
            </Field>
            <Button type="submit" level="primary" class="!mt-4" loading={loading()} disabled={loading()}>
              {t("account.login.title")}
            </Button>
          </Form>
          <Divider class="md:hidden" />
          <Divider class="hidden md:inline-block" direction="vertical" />
          <div class="md:w-0 flex-1 flex-shrink-0 flex flex-col items-center space-y-2">
            <div class="flex-1 flex flex-col items-center justify-center">
              <Switch fallback={<LogoAnimate class="w-36 h-36 hidden md:inline-block my-6" />}>
                <Match when={mascot() === xdsecMascotNormal}>
                  <img
                    src={xdsecMascotNormal}
                    class="w-36 h-36 hidden md:inline-block my-6"
                    alt="Illustrated by hypnotics"
                    title="Illustrated by hypnotics"
                  />
                  <label>{t("account.login.accountMascotTip")}</label>
                </Match>
                <Match when={mascot() === xdsecMascotUnsee}>
                  <img
                    src={xdsecMascotUnsee}
                    class="w-36 h-36 hidden md:inline-block my-6"
                    alt="Illustrated by hypnotics"
                    title="Illustrated by hypnotics"
                  />
                  <label>{t("account.login.passwordMascotTip")}</label>
                </Match>
                <Match when={mascot() === xdsecMascotHappy}>
                  <img
                    src={xdsecMascotHappy}
                    class="w-36 h-36 hidden md:inline-block my-6"
                    alt="Illustrated by hypnotics"
                    title="Illustrated by hypnotics"
                  />
                  <label>{t("account.login.successMascotTip")}</label>
                </Match>
                <Match when={mascot() === xdsecMascotCrying}>
                  <img
                    src={xdsecMascotCrying}
                    class="w-36 h-36 hidden md:inline-block my-6"
                    alt="Illustrated by hypnotics"
                    title="Illustrated by hypnotics"
                  />
                  <label>{t("account.login.failMascotTip")}</label>
                </Match>
              </Switch>
            </div>
            <Link class="w-full" href="/account/register">
              {t("account.register.tips")}
            </Link>
            <Show when={authConfig().oauth_keys !== null && (oauthServices().length || 0) > 0}>
              <div class="flex flex-row flex-wrap space-x-2 items-start w-full">
                <Show when={oauthServices().find((s) => s === "xdu")}>
                  <Link
                    class="flex-1"
                    href={`https://ids.xidian.edu.cn/authserver/login?service=${window.location.origin}/account/oauth?service=xdu`}
                    title={t("account.oauth.xdu.title")}
                  >
                    <img src={xdu} alt="XDU" width={24} height={24} />
                    <span>XDU</span>
                  </Link>
                </Show>
                <Show when={oauthServices().find((s) => s === "xmu")}>
                  <Link
                    class="flex-1"
                    href={`https://ids.xmu.edu.cn/authserver/login?service=${window.location.origin}/account/oauth?service=xmu`}
                    title={t("account.oauth.xmu.title")}
                  >
                    <img src={xmu} alt="XMU" width={24} height={24} />
                    <span>XMU</span>
                  </Link>
                </Show>
                {/* <Show when={(authConfig().oauth_keys || []).find((s) => s.service === "google")}>
                  <Link href="/account/oauth?type=redirect&service=google" square>
                    <Google width={24} height={24} />
                  </Link>
                </Show>
                <Show when={(authConfig().oauth_keys || []).find((s) => s.service === "github")}>
                  <Link href="/account/oauth?type=redirect&service=github" square>
                    <Github width={24} height={24} />
                  </Link>
                </Show>
                <Show when={(authConfig().oauth_keys || []).find((s) => s.service === "gitlab")}>
                  <Link href="/account/oauth?type=redirect&service=gitlab" square>
                    <Gitlab width={24} height={24} />
                  </Link>
                </Show> */}
              </div>
            </Show>
          </div>
        </Card>
      </div>
    </>
  );
}

// web/src/routes/account/login/+page.svelte
<script lang="ts">
  import RxButton from '$lib/components/RxButton.svelte'
  import RxCard from '$lib/components/RxCard.svelte'
  import RxForm from '$lib/components/RxForm.svelte'
  import RxFormItem from '$lib/components/RxFormItem.svelte'
  import RxInput from '$lib/components/RxInput.svelte'
  import Logo from '$lib/assets/logo.svg'
  import { platform } from '$lib/stores/platform'
  import { i18n } from '$lib/i18n'
  import { z } from 'zod'
  import { validator } from '@felte/validator-zod'
  import { createForm } from 'felte'
  import Captcha from '$lib/blocks/Captcha.svelte'
  import RxLink from '$lib/components/RxLink.svelte'
  import { login } from '$lib/api/account'
  import { goto } from '$app/navigation'
  import { showMessage } from '$lib/stores/toast'
  import type { AxiosError } from 'axios'
  import GitHub from '$lib/assets/brands/github.svelte'
  import Google from '$lib/assets/brands/google.svelte'
  import GitLab from '$lib/assets/brands/gitlab.svelte'
  import QQ from '$lib/assets/brands/qq.svelte'
  import XDU from '$lib/assets/brands/xdu.svelte'
  import { page } from '$app/stores'

  let schema = z.object({
    account: z
      .string()
      .trim()
      .min(2, { message: $i18n.t('account.accountTooShort') })
      .max(32, { message: $i18n.t('account.accountTooLong') }),
    password: z
      .string()
      .trim()
      .min(8, { message: $i18n.t('account.passwordTooShort') })
      .regex(/^(?=.*[a-z])(?=.*[A-Z])(?=.*\d)[^]{8,40}$/, { message: $i18n.t('account.passwordTooWeak') }),
    captcha_id: z.string().trim(),
    captcha_answer: z
      .string()
      .trim()
      .min(1, { message: $i18n.t('account.captchaIsRequired') }),
  })
  let loading = false
  let captcha: Captcha | null
  const { form, data, touched, errors } = createForm({
    extend: validator({ schema }),
    onSubmit(values) {
      loading = true
      return login({ ...values })
    },
    onSuccess() {
      loading = false
      showMessage('success', $i18n.t('account.loginSuccess'), 5000)
      goto($page.url.searchParams.get('redirect') || '/', { replaceState: true })
    },
    onError(error) {
      loading = false
      showMessage('error', $i18n.t('account.loginFailed') + ': ' + (error as AxiosError).response?.data, 5000)
      captcha?.refreshAll()
    },
  })

  const captchaAnswerValue = $data.captcha_answer
  $: {
    // console.log('answer', captchaAnswerValue, $data.captcha_answer)
    if (captchaAnswerValue !== $data.captcha_answer) {
      $touched.captcha_answer = true
    }
  }

  const captchaIdValue = $data.captcha_id
  $: {
    // console.log('id', captchaIdValue, $data.captcha_id)
    if (captchaIdValue !== $data.captcha_id) {
      $touched.captcha_id = true
    }
  }

  interface OAuthIds {
    github: { id: string | null }
    gitlab: { id: string | null }
    google: { id: string | null }
    qq: { id: string | null }
    xdu: { id: string | null }
  }

  let oauthIds: OAuthIds = {
    github: { id: null },
    gitlab: { id: null },
    google: { id: null },
    qq: { id: null },
    xdu: { id: null },
  }

  // iterate oauthIds and find out some id that are not null
  $: haveOauthIds = Object.values(oauthIds).some((v) => v.id !== null)
</script>

<svelte:head><title>{$i18n.t('account.login')} - {$platform.name}</title></svelte:head>

<div class="flex-1 flex flex-col md:justify-center items-center p-3 lg:p-6">
  <RxCard class="flex flex-col md:flex-row w-full max-w-4xl">
    <div class="md:w-0 flex-1 flex-col">
      <h1 class="text-center font-bold text-base">{$i18n.t('account.login')}</h1>
      <RxForm {form}>
        <RxFormItem
          name="account"
          label={$i18n.t('account.account')}
          hasError={$errors.account !== null}
          errors={$errors.account}
        >
          <RxInput
            icon="icon-[fluent--person-20-regular]"
            class="w-full"
            id="account"
            name="account"
            hasError={$errors.account !== null}
            autocomplete="username"
          />
        </RxFormItem>
        <RxFormItem name="password" label="" hasError={$errors.password !== null} errors={$errors.password}>
          <span slot="label" class="text-sm font-bold opacity-60 flex flex-row justify-between w-full">
            <span>{$i18n.t('account.password')}</span>
            <a class="hover:underline" href="/account/forgot-password">{$i18n.t('account.forgotPassword')}</a>
          </span>
          <RxInput
            icon="icon-[fluent--lock-20-regular]"
            class="w-full"
            id="password"
            type="password"
            name="password"
            hasError={$errors.password !== null}
            autocomplete="current-password"
          />
        </RxFormItem>
        <Captcha
          bind:this={captcha}
          hasError={$errors.captcha_answer !== null}
          errors={$errors.captcha_answer}
          bind:captchaId={$data.captcha_id}
          bind:captchaAnswer={$data.captcha_answer}
        />
        <RxFormItem name="submitAction" label="">
          <RxButton class="w-full" level="primary" type="submit" {loading}>{$i18n.t('account.login')}</RxButton>
        </RxFormItem>
      </RxForm>
    </div>
    <div class="divider md:divider-horizontal opacity-60">{$i18n.t('misc.or')}</div>
    <div class="md:w-0 flex-1 flex flex-col space-y-6">
      <div class="flex-1 md:flex flex-col justify-center items-center hidden">
        <img class="object-fit max-h-40" src={Logo} alt="Ret2Shell" />
      </div>
      <RxLink class="w-full" href="/account/register">{$i18n.t('account.registerTips')}</RxLink>
      {#if haveOauthIds}
        <div class="divider opacity-60">{$i18n.t('account.3rdAuth')}</div>
        <div class="w-full flex flex-row space-x-2 justify-between">
          {#if oauthIds.xdu.id !== null}
            <RxLink
              href={`https://ids.xidian.edu.cn/authserver/login?service=${$page.url.origin}/account/oauth%3Fprovider=xdu%26action=login`}
              square
              title="西安电子科技大学 统一身份认证"
            >
              <XDU width={32} height={32} />
            </RxLink>
          {/if}
          {#if oauthIds.github.id !== null}
            <RxLink
              href={`https://github.com/login/oauth/authorize?client_id=${oauthIds.github.id}&redirect_uri=${$page.url.origin}/account/oauth%3Fprovider=github%26action=login`}
              title="GitHub Accounts"
              square
            >
              <GitHub />
            </RxLink>
          {/if}
          {#if oauthIds.gitlab.id !== null}
            <RxLink href="" square title="GitLab Accounts"><GitLab /></RxLink>
          {/if}
          {#if oauthIds.google.id !== null}
            <RxLink href="" square title="Google Accounts"><Google /></RxLink>
          {/if}
          {#if oauthIds.qq.id !== null}
            <RxLink href="" title="QQ账号登录" square><QQ /></RxLink>
          {/if}
        </div>
      {/if}
    </div>
  </RxCard>
</div>
