// web/src/routes/users/[user]/_blocks/sidebar.tsx
import { mediaPath } from "@lib/utils/media";
import { type User, permissionToString } from "@models/user";
import { fullTheme, t } from "@storage/theme";
import Avatar from "@widgets/avatar";
import Divider from "@widgets/divider";
import Tag from "@widgets/tag";
import { OverlayScrollbarsComponent } from "overlayscrollbars-solid";
import { For } from "solid-js";

export default function (props: { user: User | null; loading?: boolean }) {
  return (
    <div class="w-full h-full overflow-hidden">
      <OverlayScrollbarsComponent
        options={{
          scrollbars: {
            theme: `os-theme-${fullTheme()}`,
            autoHide: "scroll",
          },
        }}
        class="relative w-full h-full print:h-auto print:overflow-auto"
        defer
      >
        <div class="flex flex-col min-h-full space-y-2 p-3 lg:p-6">
          <div class="flex flex-row space-x-4 lg:space-x-6 p-2 lg:p-4 items-center">
            <Avatar
              class="w-12 h-12 flex-shrink-0"
              src={(props.user?.avatar && mediaPath(props.user?.avatar)) || undefined}
              fallback={props.user?.nickname}
              loading={props.loading}
            />
            <div class="flex-1 flex flex-col space-y-1 justify-center overflow-hidden">
              <h2 class="font-bold w-full text-start truncate">{props.user?.nickname}</h2>
              <p class="opacity-60 w-full text-start truncate">
                <span>{props.user?.account}</span>
                <span>#</span>
                <span>{props.user?.id.toString(16).padStart(6, "0")}</span>
              </p>
            </div>
          </div>
          <Divider />
          <div class="flex flex-row space-x-2 items-center px-2 py-2">
            <span class="icon-[fluent--mail-20-regular] w-5 h-5" />
            <a
              class={`font-bold ${props.user?.email ? "hover:underline" : "blur pointer-events-none"}`.trim()}
              href={`mailto:${props.user?.email}`}
            >
              {props.user?.email ?? "fake.email@ret.sh.cn"}
            </a>
          </div>
          <Divider />
          <div class="flex flex-row space-x-2 items-center px-2 py-2">
            <span class="icon-[fluent--hat-graduation-20-regular] w-5 h-5" />
            <span class="font-bold">{props.user?.institute_name ?? t("user.noInstitute")}</span>
          </div>
          <Divider />
          <div class="flex flex-row flex-wrap">
            <For each={props.user?.permissions || []}>
              {(permission) => (
                <Tag level="info" class="m-1">
                  <span>{permissionToString(permission)}</span>
                </Tag>
              )}
            </For>
          </div>
          <div class="flex-1" />
          <div class="h-12 flex items-center justify-center">
            <span class="opacity-60">
              {t("user.registeredAt", { time: props.user?.registered_at.toFormat("yyyy-MM-dd") || "UNKNOWN" })}
            </span>
          </div>
        </div>
      </OverlayScrollbarsComponent>
    </div>
  );
}

// web/src/routes/wiki/Sidebar.svelte
<script lang="ts">
  import { getWikiList } from '$lib/api/wiki'
  import WikiTree from '$lib/blocks/WikiTree.svelte'
  import { i18n } from '$lib/i18n'
  import { transformToWikiEntry, type WikiEntry } from '$lib/models/wiki'
  import { theme } from '$lib/stores/theme'
  import { OverlayScrollbarsComponent } from 'overlayscrollbars-svelte'

  export let wiki: WikiEntry[]
  export let activeChains: number[] = []
  export let loading: boolean

  async function fetchChildren(id: number) {
    return transformToWikiEntry(await getWikiList(id))
  }
</script>

<h1
  class="h-16 bg-neutral/10 backdrop-blur border-b border-b-base-content/5 flex flex-row items-center justify-center space-x-2 p-4 font-bold sticky top-0 z-10"
>
  <span class="w-6 h-6 icon-[fluent--hat-graduation-16-regular]" />
  <span>
    {$i18n.t('wiki.sideToc')}
  </span>
</h1>
<OverlayScrollbarsComponent
  options={{
    scrollbars: { theme: $theme.colorScheme === 'light' ? 'os-theme-dark' : 'os-theme-light', autoHide: 'scroll' },
  }}
  class="w-full flex-1 flex flex-col relative print:hidden"
  defer
>
  {#if loading}
    <div class="flex flex-row justify-center items-center h-16 space-x-2">
      <span class="loading loading-spinner loading-sm" />
      <span class="text-base">{$i18n.t('wiki.fetchingList')}</span>
    </div>
  {:else}
    {#if wiki.length === 0}
      <p class="text-base font-semibold p-4 opacity-60 text-center">{$i18n.t('playground.emptyCategory')}</p>
    {/if}
    <div class="p-4">
      <WikiTree bind:tree={wiki} {activeChains} addrPrefix="/wiki" {fetchChildren} manageBtn={false} />
    </div>
  {/if}
</OverlayScrollbarsComponent>
