// web/src/lib/blocks/Captcha.svelte
<script lang="ts">
  import RxButton from '$lib/components/RxButton.svelte'
  import RxInput from '$lib/components/RxInput.svelte'
  import RxImage from '$lib/components/RxImage.svelte'
  import { i18n } from '$lib/i18n'
  import RxFormItem from '$lib/components/RxFormItem.svelte'
  import { onMount } from 'svelte'
  import { getCaptcha } from '$lib/api/account'
  import type { Captcha } from '$lib/models/captcha'
  import { Validator } from '$lib/models/config'
  import { encode } from 'js-base64'

  export let hasError = false
  export let errors: string | string[] | undefined = undefined
  export let captchaId: string | unknown | undefined = undefined
  export let captchaAnswer: string | unknown | undefined = undefined
  let loading = true
  let failed = false
  export let enabled = true
  let powing = true
  let fetchingPow = true
  let fetchingImg = true
  let captcha: Captcha

  function refreshImg() {
    fetchingImg = true
    refresh()
  }

  export function refreshAll() {
    loading = true
    refresh()
  }

  function refreshPow() {
    fetchingPow = true
    refresh()
  }

  function refresh() {
    getCaptcha().then((res) => {
      if (res.status !== 200) {
        failed = true
        loading = false
        return
      }
      res.json().then((data) => {
        captcha = data
        captchaId = captcha.id
        failed = false
        loading = false
        fetchingImg = false
        fetchingPow = false
      })
    })
  }

  $: {
    if (captcha && captcha.validator === Validator.Pow) {
      powing = true
      const worker = new Worker(new URL('$lib/workers/pow.worker.ts', import.meta.url), { type: 'module' })
      worker.postMessage({
        challenge: captcha.challenge,
      })
      worker.onmessage = (e) => {
        powing = false
        captchaAnswer = e.data
        worker.terminate()
      }
    }
  }

  onMount(() => {
    refresh()
  })
</script>

<RxFormItem label={$i18n.t('form.captcha')} name="captcha_answer" class="" {hasError} {errors}>
  {#if loading || failed}
    <RxButton {loading} class="w-full" disabled={loading} on:click={refreshAll}>
      {loading ? $i18n.t('form.loadingCaptcha') : $i18n.t('form.reloadCaptcha')}
    </RxButton>
  {:else if enabled && !loading && !failed && captcha.validator === Validator.Pow}
    <RxInput
      icon="icon-[fluent--beaker-16-regular]"
      class="w-full"
      type="text"
      {hasError}
      disabled
      bind:value={captchaAnswer}
      placeholder="0XDEADBEEF######"
    >
      <RxButton loading={powing} disabled={powing || fetchingPow} on:click={refreshPow}>
        {fetchingPow ? $i18n.t('form.fetchingPow') : powing ? $i18n.t('form.powing') : ''}
        {#if !fetchingPow && !powing}
          <span class="icon-[fluent--checkmark-16-regular] w-6 h-6 text-success" />
        {/if}
      </RxButton>
    </RxInput>
  {:else if enabled && !loading && !failed && captcha.validator === Validator.Image}
    <RxInput icon="icon-[fluent--beaker-16-regular]" class="w-full" type="text" {hasError} bind:value={captchaAnswer}>
      <RxButton class="border-none w-24 p-0 overflow-hidden" disabled={fetchingImg} on:click={refreshImg}>
        <RxImage
          class="w-full object-scale-down"
          loading={fetchingImg}
          src={`data:image/svg+xml;base64,${encode(captcha.challenge, false)}`}
        />
      </RxButton>
    </RxInput>
  {/if}
</RxFormItem>

// web/src/lib/blocks/captcha.tsx
import { getCaptcha } from "@api/account";
import Spin from "@assets/animates/spin";
import type { Captcha } from "@models/captcha";
import { type FormStore, type Maybe, setValue } from "@modular-forms/solid";
import { t } from "@storage/theme";
import Button from "@widgets/button";
import Input, { type TextInputProps } from "@widgets/input";
import { encode } from "js-base64";
import { type ComponentProps, createEffect, createSignal, splitProps, untrack } from "solid-js";

export default function (
    props: TextInputProps &
        ComponentProps<"input"> & {
            // biome-ignore lint/suspicious/noExplicitAny: the options are not ensured
            captchaForm: FormStore<any, undefined>;
            idFieldValue: Maybe<string>;
            idFieldError: string | undefined;
            answerFieldValue: Maybe<string>;
            answerFieldError: string | undefined;
            timestamp?: number;
        }
) {
    const [fieldProps, inputProps] = splitProps(props, ["idFieldValue", "answerFieldValue"]);
    const [captcha, setCaptcha] = createSignal<Captcha | null>(null);
    const [loading, setLoading] = createSignal(true);
    const [calculating, setCalculating] = createSignal(false);
    const [manuallyFill, setManuallyFill] = createSignal(true);

    function reload() {
        setLoading(true);
        getCaptcha()
            .then((resp) => {
                setCaptcha(resp);
                if (resp.validator === "pow") startPow();
                else if (resp.validator === "none") {
                    setValue(props.captchaForm, "captcha_answer", "0xDEADBEEF");
                }
                setValue(props.captchaForm, "captcha_id", resp.id);
            })
            .catch(() => {
                setCaptcha(null);
                setValue(props.captchaForm, "captcha_id", "");
            })
            .finally(() => {
                setLoading(false);
                setValue(props.captchaForm, "captcha_answer", "");
            });
    }

    createEffect(() => {
        if (props.timestamp) {
            untrack(reload);
        }
    });

    function getCaptchaContent() {
        const captchaObj = captcha();
        if (captchaObj)
            switch (captchaObj.validator) {
                case "none":
                    setManuallyFill(false);
                    return <span>NONE</span>;
                case "image":
                    setManuallyFill(true);
                    return (
                        <img
                            class="w-20 object-fill"
                            src={`data:image/svg+xml;base64,${encode(captchaObj.challenge)}`}
                            alt={t("captcha.reload")}
                        />
                    );
                case "pow":
                    setManuallyFill(false);
                    return (
                        <span class="inline-flex space-x-2 items-center">
                            {calculating() ? (
                                <>
                                    <Spin width={20} height={20} />
                                    <span>{t("captcha.calculating")}</span>
                                </>
                            ) : (
                                <span class="icon-[fluent--checkmark-20-regular] w-5 h-5 text-success" />
                            )}
                        </span>
                    );
                case "recaptcha_v3":
                    setManuallyFill(false);
                    return <span>ReCaptcha V3</span>;
                case "h_captcha":
                    setManuallyFill(false);
                    return <span>HCaptcha</span>;
            }
    }

    function startPow() {
        setCalculating(true);
        const worker = new Worker(new URL("@lib/workers/pow.worker.ts", import.meta.url), { type: "module" });
        worker.postMessage({
            challenge: captcha()?.challenge,
        });
        worker.onmessage = (e) => {
            setCalculating(false);
            setValue(props.captchaForm, "captcha_answer", e.data);
            worker.terminate();
        };
    }

    return (
        <>
            <input class="hidden" name="captcha_id" value={fieldProps.idFieldValue} />
            <Input
                icon={<span class="icon-[fluent--bot-20-regular] w-5 h-5" />}
                placeholder={t("captcha.placeholder")}
                title={t("captcha.placeholder")}
                value={fieldProps.answerFieldValue}
                {...inputProps}
                disabled={!manuallyFill()}
                error={props.idFieldError || props.answerFieldError}
                extraBtn={
                    <Button
                        class="!rounded-l-none"
                        loading={loading()}
                        onClick={reload}
                        disabled={calculating() || loading()}
                        type="button"
                    >
                        {loading() ? t("captcha.loading") : captcha() ? getCaptchaContent() : t("captcha.loadFailed")}
                    </Button>
                }
            />
        </>
    );
}
