// web/src/routes/admin/captcha/index.tsx
import { handleHttpError } from "@api";
import { getPlatformConfig, updatePlatformConfig } from "@api/platform";
import type { CaptchaConfig, Config } from "@models/config";
import { createForm, getValue, required, setValues } from "@modular-forms/solid";
import { Title } from "@storage/header";
import { t } from "@storage/theme";
import { addToast } from "@storage/toast";
import Button from "@widgets/button";
import Checkbox from "@widgets/checkbox";
import Select from "@widgets/select";
import Slider from "@widgets/slider";
import type { HTTPError } from "ky";
import { createSignal, onMount } from "solid-js";

export default function () {
  const [form, { Form, Field }] = createForm<CaptchaConfig>();
  const [loading, setLoading] = createSignal(false);
  const [config, setConfig] = createSignal(null as null | Config);
  onMount(async () => {
    try {
      const resp = await getPlatformConfig();
      setConfig(resp);
      setValues(form, {
        enabled: resp.captcha.enabled,
        difficulty: resp.captcha.difficulty,
        validator: resp.captcha.validator,
      });
    } catch (err) {
      handleHttpError(err as HTTPError, t("errors.500")!);
    }
  });
  async function onSubmit(result: CaptchaConfig) {
    setLoading(true);
    if (!config()) {
      addToast({
        level: "error",
        description: t("admin.platform.fetchNotReady")!,
        duration: 5000,
      });
      return;
    }
    const mergedConfig = {
      ...config(),
      captcha: {
        enabled: result.enabled,
        difficulty: result.difficulty,
        validator: result.validator,
      },
    } as Config;
    try {
      await updatePlatformConfig(mergedConfig);
      setConfig(mergedConfig);
      addToast({
        level: "success",
        description: t("admin.platform.updateSuccess")!,
        duration: 5000,
      });
    } catch (err) {
      handleHttpError(err as HTTPError, t("admin.platform.updateFailed")!);
    }
    setLoading(false);
  }
  return (
    <>
      <Title page={t("admin.captcha.title")} route="/admin/captcha" />
      <div class="flex-1 flex flex-col items-center p-3 lg:p-6">
        <Form onSubmit={onSubmit} class="w-full max-w-5xl flex flex-col space-y-2">
          <h3 class="h-12 flex items-center border-b border-b-layer-content/10 font-bold space-x-2">
            <span class="icon-[fluent--settings-20-regular] w-5 h-5" />
            <span>{t("admin.captcha.title")}</span>
          </h3>
          <div class="flex flex-col space-y-2 lg:flex-row lg:space-y-0 lg:space-x-2 lg:items-end">
            <Field name="enabled" type="boolean">
              {(field, props) => (
                <Checkbox
                  class="flex-1"
                  inputProps={props}
                  checked={field.value}
                  error={field.error}
                  title={t("captcha.enabled")}
                >
                  <span class="flex-1 text-start">{t("captcha.enabled")}</span>
                </Checkbox>
              )}
            </Field>
            <Field name="validator" validate={[required(t("admin.captcha.validatorRequired")!)]}>
              {(field, props) => (
                <Select
                  name={field.name}
                  label={t("admin.captcha.validator")!}
                  disabled={getValue(form, "enabled") === false}
                  class="flex-1"
                  error={field.error}
                  placeholder={t("admin.captcha.select")}
                  items={[
                    {
                      value: "pow",
                      label: t("admin.captcha.pow")!,
                      icon: "icon-[fluent--code-20-regular]",
                    },
                    {
                      value: "image",
                      label: t("admin.captcha.image")!,
                      icon: "icon-[fluent--image-20-regular]",
                    },
                  ]}
                  value={field.value ? [field.value as string] : undefined}
                  inputProps={props}
                />
              )}
            </Field>
          </div>
          <Field name="difficulty" type="number">
            {(field, props) => (
              <Slider
                disabled={getValue(form, "enabled") === false}
                class="flex-1"
                label={t("admin.captcha.difficulty")!}
                max={10}
                min={1}
                step={1}
                name={field.name}
                value={[field.value || 1]}
                inputProps={props}
              />
            )}
          </Field>
          <Button type="submit" level="primary" class="!mt-4" loading={loading()} disabled={!config() || loading()}>
            {t("form.save")}
          </Button>
        </Form>
      </div>
    </>
  );
}

// web/src/routes/admin/platform/captcha/+page.svelte
<script lang="ts">
    import { platform } from '$lib/stores/platform'
    import { i18n } from '$lib/i18n'
    import RxForm from '$lib/components/RxForm.svelte'
    import { z } from 'zod'
    import { validator } from '@felte/validator-zod'
    import { createForm } from 'felte'
    import RxFormItem from '$lib/components/RxFormItem.svelte'
    import RxInput from '$lib/components/RxInput.svelte'
    import RxCheckBox from '$lib/components/RxCheckBox.svelte'
    import RxRadioGroup from '$lib/components/RxRadioGroup.svelte'
    import RxButton from '$lib/components/RxButton.svelte'
    import type { Config, Validator } from '$lib/models/config'
    import { onMount } from 'svelte'
    import { getPlatformConfig, setPlatformConfig } from '$lib/api/platform'
    import type { Obj } from '@felte/core'
    import { user } from '$lib/stores/user'
    import { showMessage } from '$lib/stores/toast'
    import type { AxiosError } from 'axios'

    let schema = z.object({
      enabled: z.boolean(),
      difficulty: z
        .number()
        .min(1, { message: $i18n.t('init.captchaDifficultyMinLimit') })
        .max(9, { message: $i18n.t('init.captchaDifficultyMaxLimit') }),
      validator: z
        .number()
        .min(1, { message: $i18n.t('init.captchaValidatorLimit') })
        .max(2, { message: $i18n.t('init.captchaValidatorLimit') }),
    })
    let loading = false
    let platformConfig:Config = {}
    const { form, data, touched, errors } = createForm({
      extend: validator({ schema }),
      onSubmit(values) {
        const payload: Config = {
            ...platformConfig,
            captcha: values,
        } as Config
      setPlatformConfig(payload, $user.token)
        .then(() => {
          showMessage('success', $i18n.t('admin.config.saved'), 5000)
        })
        .catch((error) => {
          showMessage('error', `${$i18n.t('admin.config.saveFailed')}: ${(error as AxiosError).response?.data}`, 5000)
        })
      return Promise.resolve()
        }
    })
    const validatorValue = $data.validator
    $: {
      if (validatorValue !== $data.validator) {
        $touched.validator = true
      }
    }
    onMount(() => {
        getPlatformConfig()
        .then((res) => {
        platformConfig = res
        data.update(() => {
            return res.captcha as unknown as Obj
        })
        loading = false
      })
    })
  </script>
  
  <svelte:head><title>{$i18n.t('init.captchaTitle')} - {$platform.name}</title></svelte:head>
  <div class="flex-1 flex flex-row p-4 lg:p-6 justify-center">
    <div class="flex-1 flex flex-col max-w-5xl">
      <div class="m-2 md:m-4 flex flex-row justify-center items-center space-x-6">
        <span class="icon-[fluent--chevron-double-right-16-regular] opacity-60" />
        <h1 class="text-2xl font-bold">{$i18n.t('init.captchaTitle')}</h1>
        <span class="icon-[fluent--chevron-double-left-16-regular] opacity-60" />
      </div>
      <RxForm {form}>
        <RxFormItem name="enabled" label="" hasError={$errors.enabled !== null} errors={$errors.enabled || ''}>
          <RxCheckBox id="enabled" name="enabled" checked={platformConfig.captcha?.enabled} label={$i18n.t('init.captchaEnabled')} />
        </RxFormItem>
        <RxFormItem
          name="difficulty"
          label={$i18n.t('init.captchaDifficulty')}
          hasError={$errors.difficulty !== null}
          errors={$errors.difficulty || ''}
        >
          <RxInput
            icon="icon-[fluent--hand-left-16-regular]"
            class="w-full"
            id="difficulty"
            name="difficulty"
            hasError={$errors.difficulty !== null}
            placeholder={$i18n.t('init.captchaDifficultyPlaceholder')}
            value={platformConfig.captcha?.difficulty}
            type="number"
          />
        </RxFormItem>
        <RxFormItem
          name="validator"
          label={$i18n.t('init.captchaValidator')}
          hasError={$errors.validator !== null}
          errors={$errors.validator || ''}
        >
          <RxRadioGroup
            class="w-full"
            direction="row"
            items={[
              { label: $i18n.t('init.captchaValidatorImage'), value: 1 },
              { label: $i18n.t('init.captchaValidatorPow'), value: 2 },
            ]}
            bind:value={$data.validator}
          />
        </RxFormItem>
        <RxFormItem name="submitAction" label="">
          <RxButton class="w-full" level="primary" type="submit">{$i18n.t('admin.config.submit')}</RxButton>
        </RxFormItem>
      </RxForm>
    </div>
  </div>
